id: I4BF6663C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T19:57:26+00:00'
last_modified: '2022-06-10T04:42:46.408797+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29987
  title: སློབ་འབྲིང་བོད་ཡིག་སློབ་ཐབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E305:
      image_group_id: I1KG22659
      title: Volume 1 of slob 'bring bod yig slob thabs
      total_pages: 466
      order: 1
      base_file: E305.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
